### ISSUE TITLE
Correct autoload?

### ISSUE THREAD

**Issue by NoMan2000** [OzzyCzech/potrans#3]
On line 12 of potranscli.php it references this:

    require_once __DIR__ . '/../vendor/autoload.php';

But that has no reference, there is no autoloader.php file inside of the root of the project.  Unless I'm missing something, either you need to add one or use the default one with composer.

The vendor root is at least three levels above this one, (vendor/om/src/potranscli.php), so the correct path should be:

    require_once __DIR__ . '/../../../autoload.php';

**Comment by NoMan2000** [comment]
Also it gave me a server error when I tried to run it, even as sudo, but there was no debug output even with verbose enabled.  It just said "Server Error".

**Comment by OzzyCzech** [comment]
I am using [PHP composer](https://getcomposer.org/), run `composer install` in potrans root and autoloader file will be generated.

**Comment by oezgueng** [comment]
i have the same problem...
403 error.... someone resolve this bug?
