### ISSUE TITLE
Error "Server Error #403: "

### ISSUE THREAD

**Issue by nobicycle** [OzzyCzech/potrans#5]
Hello OzzyCzech

I get the following:

$potrans -k -i ~/Downloads/health_inpatient.pot -o health_inpatient-id.pot -f en -t id
Translating : 345 entries from en to id
Error "Server Error #403: 

Arch linux is now on php version 7
php -v
PHP 7.0.5 (cli) (built: Mar 29 2016 18:07:10) ( NTS )

But I also have:
$ php56 -v
PHP 5.6.20 (cli) (built: Apr 23 2016 11:45:06)

I followed the instructions for both php and php56 but in both cases the error is the same.

Changing the install slightly, I then changed 'composer install' to php56 composer.phar install.
Still the error was the same

Thanks for the app by the way.

Best wishes

**Comment by ocgltd** [comment]
I just had the same issue, with the potrans stopping after the 10 strings.

It turns out the script is hitting the google API too quickly.  Add a 1 second delay in the php loop and then it runs great!  (As of Jan 2020)

**Comment by quinncomendant** [comment]
Hey @nobicycle, you included your API key in your original post, which means anyone could use it to run up charges in your Google account. You should delete this key at https://console.developers.google.com/ and generate a new one.

**Comment by nobicycle** [comment]
> Hey @nobicycle, you included your API key in your original post, 

Thanks

**Comment by OzzyCzech** [comment]
There is new -w or --wait parameter that should help, but Google seems response really fast
