### ISSUE TITLE
Error "Server Error #403: "

### ISSUE THREAD

**Issue by stilcom** [OzzyCzech/potrans#9]
Hello,
I followed all needed steps to set up POTRANS but when I run it like this :
 php bin/potrans -k 1234567890 -i fr_FR.po -o fr_FR_trans.po -f en -t fr
Translating : 1512 entries from en to fr

It dumps this error:
Error "Server Error #403: "

What does it mean and how to fix this?
I tried the 'sleep(1)' hint from another thread but this does not help at all.

Thanks for your precious help
Hacen

**Comment by OzzyCzech** [comment]
There is new `-w` or `--wait` parameter that should help, but Google seems response really fast
